const express = require('express');
const userRouter = express.Router();
const User = require('../models/user'); // Assuming you have a User model

// ...existing code...

userRouter.post('/api/user/update-questions', async (req, res) => {
  try {
    //userId is not email . Its the Id generated by mongodb
    const { userId, totalQuestions } = req.body;
    const user = await User.findByIdAndUpdate(
      userId,
      { totalQuestions },
      { new: true }
    );
    res.json(user);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

// ...existing code...

module.exports = userRouter;